import { PlanSubscription, PricingPlan } from './nest-types/modules/app-pricing/types/app-pricing.enum';
import { LocationConditionEnum } from './nest-types/modules/rule/types/rule.enum';
import { SortOptionsEnum } from './nest-types/modules/shop/entities/shop-general.entity';
import {
  CartPageDateDisplayType,
  CountdownTimerOption,
  DateCalculationMethod,
  DateDisplayMode,
  DateRangeDirection,
  DetectionMethod,
  ShopLayout,
} from './nest-types/modules/shop/types/shop.enum';
import { IShopifyAppMetafieldPayload } from './nest-types/shared/api/types/shopify-api/shopify-api.interface';

export const DEFAULT_TIMEZONE = 'Default customer timezone';

export const REGION_COUNTRIES: Record<string, string> = {
  All: 'All',
  NorthAmerica: 'AI,AG,AW,BS,BB,BZ,BM,VG,CA,BQ,KY,CR,CW,DM,DO,SV,GL,GD,GP,GT,HT,HN,JM,MQ,MX,MS,NI,PA,MF,BL,KN,LC,PM,VC,TT,TC,US',
  SouthAmerica: 'AR,BO,BR,CL,CO,EC,FK,GF,GY,PY,PE,GS,SR,UY,VE',
  EU: 'AT,BE,BG,HR,CY,CZ,DK,EE,FI,FR,DE,GR,HU,IE,IT,LV,LT,LU,MT,NL,PL,PT,RO,SK,SI,ES,SE',
  SEA: 'BN,KH,TL,ID,LA,MY,MM,PH,SG,TH,VN',
  EastAsia: 'CN,JP,MN,KP,KR,TW',
  SouthAsia: 'AF,BD,BT,IN,MV,NP,PK,LK',
  WestAsia: 'BH,CY,GE,IR,IQ,IL,JO,KW,LB,OM,PS,QA,SA,SY,TR,AE,YE',
  AllCountriesInAllRegion:
    'BH,CY,GE,IR,IQ,IL,JO,KW,LB,OM,PS,QA,SA,SY,TR,AE,YE,AF,BD,BT,IN,MV,NP,PK,LK,CN,JP,MN,KP,KR,TW,BN,KH,TL,ID,LA,MY,MM,PH,SG,TH,VN,AI,AG,AW,BS,BB,BZ,BM,VG,CA,BQ,KY,CR,CW,DM,DO,SV,GL,GD,GP,GT,HT,HN,JM,MQ,MX,MS,NI,PA,MF,BL,KN,LC,PM,VC,TT,TC,US,AR,BO,BR,CL,CO,EC,FK,GF,GY,PY,PE,GS,SR,UY,VE,AT,BE,BG,HR,CY,CZ,DK,EE,FI,FR,DE,GR,HU,IE,IT,LV,LT,LU,MT,NL,PL,PT,RO,SK,SI,ES,SE,',
};

export const DATE_LOCALE_TRANSLATES = [
  { locale: 'af', language: 'Afrikaans', today: 'Vandag', tomorrow: 'Môre' },
  { locale: 'sq', language: 'Albanian', today: 'Sot', tomorrow: 'Nesër' },
  { locale: 'ar', language: 'Arabic', today: 'اليوم', tomorrow: 'غدًا' },
  { locale: 'ar-dz', language: 'Arabic (Algeria)', today: 'اليوم', tomorrow: 'غدًا' },
  { locale: 'ar-kw', language: 'Arabic (Kuwait)', today: 'اليوم', tomorrow: 'غدًا' },
  { locale: 'ar-ly', language: 'Arabic (Lybia)', today: 'اليوم', tomorrow: 'غدًا' },
  { locale: 'ar-ma', language: 'Arabic (Morocco)', today: 'اليوم', tomorrow: 'غدًا' },
  { locale: 'ar-sa', language: 'Arabic (Saudi Arabia)', today: 'اليوم', tomorrow: 'غدًا' },
  { locale: 'ar-tn', language: 'Arabic (Tunisia)', today: 'اليوم', tomorrow: 'غدًا' },
  { locale: 'hy-am', language: 'Armenian', today: 'Այսօր', tomorrow: 'Վաղը' },
  { locale: 'az', language: 'Azerbaijani', today: 'Bu gün', tomorrow: 'Sabah' },
  { locale: 'bm', language: 'Bambara', today: 'Bi', tomorrow: 'Sini' },
  { locale: 'eu', language: 'Basque', today: 'Gaur', tomorrow: 'Bihar' },
  { locale: 'be', language: 'Balarusion', today: 'Сёння', tomorrow: 'Заўтра' },
  { locale: 'bn', language: 'Bengali', today: 'আজ', tomorrow: 'আগামীকাল' },
  { locale: 'bs', language: 'Bosnian', today: 'Danas', tomorrow: 'Sutra' },
  { locale: 'br', language: 'Breton', today: 'Hiziv', tomorrow: "Warc'hoazh" },
  { locale: 'bg', language: 'Bulgarian', today: 'Днес', tomorrow: 'Утре' },
  { locale: 'my', language: 'Burmese', today: 'ယနေ့', tomorrow: 'မနက်ဖြန်' },
  { locale: 'km', language: 'Cambodian', today: 'ថ្ងៃនេះ', tomorrow: 'ថ្ងៃស្អែក' },
  { locale: 'ca', language: 'Catalan', today: 'Avui', tomorrow: 'Demà' },
  { locale: 'tzm', language: 'Central Atlas Tamazight', today: 'ⴰⵙⵙⴰ', tomorrow: 'ⴰⴽⴽⴰ' },
  { locale: 'tzm-latn', language: 'Central Atlas Tamazight Latin', today: 'Assa', tomorrow: 'Akka' },
  { locale: 'zh-cn', language: 'Chinese (China)', today: '今天', tomorrow: '明天' },
  { locale: 'zh-hk', language: 'Chinese (Hong Kong)', today: '今天', tomorrow: '明天' },
  { locale: 'zh-tw', language: 'Chinese (Taiwan)', today: '今天', tomorrow: '明天' },
  { locale: 'cv', language: 'Chuvash', today: 'Пӑн', tomorrow: 'Кӑрсаҫ' },
  { locale: 'hr', language: 'Croatian', today: 'Danas', tomorrow: 'Sutra' },
  { locale: 'cs', language: 'Czech', today: 'Dnes', tomorrow: 'Zítra' },
  { locale: 'da', language: 'Danish', today: 'I dag', tomorrow: 'I morgen' },
  { locale: 'nl', language: 'Dutch', today: 'Vandaag', tomorrow: 'Morgen' },
  { locale: 'nl-be', language: 'Dutch (Belgium)', today: 'Vandaag', tomorrow: 'Morgen' },
  { locale: 'en-au', language: 'English (Australia)', today: 'Today', tomorrow: 'Tomorrow' },
  { locale: 'en-ca', language: 'English (Canada)', today: 'Today', tomorrow: 'Tomorrow' },
  { locale: 'en-ie', language: 'English (Ireland)', today: 'Today', tomorrow: 'Tomorrow' },
  { locale: 'en-il', language: 'English (Israel)', today: 'Today', tomorrow: 'Tomorrow' },
  { locale: 'en-nz', language: 'English (New Zealand)', today: 'Today', tomorrow: 'Tomorrow' },
  { locale: 'en-gb', language: 'English (United Kingdom)', today: 'Today', tomorrow: 'Tomorrow' },
  { locale: 'en', language: 'English (United States)', today: 'Today', tomorrow: 'Tomorrow' },
  { locale: 'eo', language: 'Esperanto', today: 'Hodiaŭ', tomorrow: 'Morgaŭ' },
  { locale: 'et', language: 'Estonian', today: 'Täna', tomorrow: 'Homme' },
  { locale: 'fo', language: 'Faroese', today: 'Í dag', tomorrow: 'Í morgin' },
  { locale: 'fi', language: 'Finnish', today: 'Tänään', tomorrow: 'Huomenna' },
  { locale: 'fr', language: 'French', today: "Aujourd'hui", tomorrow: 'Demain' },
  { locale: 'fr-ca', language: 'French (Canada)', today: "Aujourd'hui", tomorrow: 'Demain' },
  { locale: 'fr-ch', language: 'French (Switzerland)', today: "Aujourd'hui", tomorrow: 'Demain' },
  { locale: 'fy', language: 'Frisian', today: 'Hjoed', tomorrow: 'Moarn' },
  { locale: 'gl', language: 'Galician', today: 'Hoxe', tomorrow: 'Mañá' },
  { locale: 'ka', language: 'Georgian', today: 'დღეს', tomorrow: 'ხვალ' },
  { locale: 'de', language: 'German', today: 'Heute', tomorrow: 'Morgen' },
  { locale: 'de-at', language: 'German (Austria)', today: 'Heute', tomorrow: 'Morgen' },
  { locale: 'de-ch', language: 'German (Switzerland)', today: 'Heute', tomorrow: 'Morgen' },
  { locale: 'el', language: 'Greek', today: 'Σήμερα', tomorrow: 'Αύριο' },
  { locale: 'gu', language: 'Gujarati', today: 'આજે', tomorrow: 'કાલે' },
  { locale: 'he', language: 'Hebrew', today: 'היום', tomorrow: 'מחר' },
  { locale: 'hi', language: 'Hindi', today: 'आज', tomorrow: 'कल' },
  { locale: 'hu', language: 'Hungarian', today: 'Ma', tomorrow: 'Holnap' },
  { locale: 'is', language: 'Icelandic', today: 'Í dag', tomorrow: 'Á morgun' },
  { locale: 'id', language: 'Indonesian', today: 'Hari ini', tomorrow: 'Besok' },
  { locale: 'ga', language: 'Irish or Irish Gaelic', today: 'Inniu', tomorrow: 'Amárach' },
  { locale: 'it', language: 'Italian', today: 'Oggi', tomorrow: 'Domani' },
  { locale: 'it-ch', language: 'Italian (Switzerland)', today: 'Oggi', tomorrow: 'Domani' },
  { locale: 'ja', language: 'Japanese', today: '今日', tomorrow: '明日' },
  { locale: 'jv', language: 'Javanese', today: 'Saiki', tomorrow: 'Sesuk' },
  { locale: 'kn', language: 'Kannada', today: 'ಇಂದು', tomorrow: 'ನಾಳೆ' },
  { locale: 'kk', language: 'Kazakh', today: 'Бүгін', tomorrow: 'Ертең' },
  { locale: 'tlh', language: 'Klingon', today: 'DaHjaj', tomorrow: "wa'leS" },
  { locale: 'gom-latn', language: 'Konkani Latin script', today: 'आज', tomorrow: 'उद्याचे' },
  { locale: 'ko', language: 'Korean', today: '오늘', tomorrow: '내일' },
  { locale: 'ku', language: 'Kurdish', today: 'ئەمڕۆ', tomorrow: 'بەیانی' },
  { locale: 'ky', language: 'Kyrgyz', today: 'Бүгүн', tomorrow: 'Эртең' },
  { locale: 'lo', language: 'Lao', today: 'ມື້ນີ້', tomorrow: 'ມື້ອື່ນ' },
  { locale: 'lv', language: 'Latvian', today: 'Šodien', tomorrow: 'Rīt' },
  { locale: 'lt', language: 'Lithuanian', today: 'Šiandien', tomorrow: 'Rytoj' },
  { locale: 'lb', language: 'Luxembourgish', today: 'Haut', tomorrow: 'Muer' },
  { locale: 'mk', language: 'Macedonian', today: 'Денес', tomorrow: 'Утре' },
  { locale: 'ms', language: 'Malay', today: 'Hari ini', tomorrow: 'Esok' },
  { locale: 'ml', language: 'Malayalam', today: 'ഇന്ന്', tomorrow: 'നാളെ' },
  { locale: 'dv', language: 'Maldivian', today: 'މިއަދު', tomorrow: 'މިއަދު' },
  { locale: 'mt', language: 'Maltese (Malta)', today: 'Illum', tomorrow: 'Għada' },
  { locale: 'mi', language: 'Maori', today: 'Tēnei rā', tomorrow: 'Āpōpō' },
  { locale: 'mr', language: 'Marathi', today: 'आज', tomorrow: 'उद्या' },
  { locale: 'mn', language: 'Mongolian', today: 'Өнөөдөр', tomorrow: 'Маргааш' },
  { locale: 'me', language: 'Montenegrin', today: 'Данас', tomorrow: 'Сутра' },
  { locale: 'ne', language: 'Nepalese', today: 'आज', tomorrow: 'भोलि' },
  { locale: 'se', language: 'Northern Sami', today: 'Dán', tomorrow: 'Bijá' },
  { locale: 'nb', language: 'Norwegian Bokmål', today: 'I dag', tomorrow: 'I morgen' },
  { locale: 'nn', language: 'Nynorsk', today: 'I dag', tomorrow: 'I morgon' },
  { locale: 'fa', language: 'Persian', today: 'امروز', tomorrow: 'فردا' },
  { locale: 'pl', language: 'Polish', today: 'Dzisiaj', tomorrow: 'Jutro' },
  { locale: 'pt', language: 'Portuguese', today: 'Hoje', tomorrow: 'Amanhã' },
  { locale: 'pt-br', language: 'Portuguese (Brazil)', today: 'Hoje', tomorrow: 'Amanhã' },
  { locale: 'x-pseudo', language: 'Pseudo', today: 'Pseudo', tomorrow: 'Pseudo' },
  { locale: 'pa-in', language: 'Punjabi', today: 'ਅੱਜ', tomorrow: 'ਕਲ' },
  { locale: 'ro', language: 'Romanian', today: 'Astăzi', tomorrow: 'Mâine' },
  { locale: 'ru', language: 'Russian', today: 'Сегодня', tomorrow: 'Завтра' },
  { locale: 'gd', language: 'Scottish Gealic', today: 'An-diugh', tomorrow: 'A-màireach' },
  { locale: 'sr', language: 'Serbian', today: 'Данас', tomorrow: 'Сутра' },
  { locale: 'sr-cyrl', language: 'Serbian Cyrillic', today: 'Данас', tomorrow: 'Сутра' },
  { locale: 'sd', language: 'Sindhi', today: 'آڄو', tomorrow: 'سنڌي' },
  { locale: 'si', language: 'Sinhalese', today: 'අද', tomorrow: 'හෙට' },
  { locale: 'sk', language: 'Slovak', today: 'Dnes', tomorrow: 'Zajtra' },
  { locale: 'sl', language: 'Slovenian', today: 'Danes', tomorrow: 'Jutri' },
  { locale: 'es', language: 'Spanish', today: 'Hoy', tomorrow: 'Mañana' },
  { locale: 'es-do', language: 'Spanish (Dominican Republic)', today: 'Hoy', tomorrow: 'Mañana' },
  { locale: 'es-us', language: 'Spanish (United States)', today: 'Hoy', tomorrow: 'Mañana' },
  { locale: 'sw', language: 'Swahili', today: 'Leo', tomorrow: 'Kesho' },
  { locale: 'sv', language: 'Swedish', today: 'Idag', tomorrow: 'Imorgon' },
  { locale: 'tl-ph', language: 'Tagalog (Philippines)', today: 'Ngayon', tomorrow: 'Bukas' },
  { locale: 'tg', language: 'Tajik', today: 'Имрӯз', tomorrow: 'Пагоҳ' },
  { locale: 'tzl', language: 'Talossan', today: 'Uei', tomorrow: 'Mach' },
  { locale: 'ta', language: 'Tamil', today: 'இன்று', tomorrow: 'நாளை' },
  { locale: 'te', language: 'Telugu', today: 'ఈ రోజు', tomorrow: 'రేపు' },
  { locale: 'tet', language: 'Tetun Dili (East Timor)', today: 'Ohin', tomorrow: 'Aban' },
  { locale: 'th', language: 'Thai', today: 'วันนี้', tomorrow: 'พรุ่งนี้' },
  { locale: 'bo', language: 'Tibetan', today: 'ད་རེས་དེ་རང་སྐྱོང་།', tomorrow: 'ནང་དང་རང་སྐྱོང་།' },
  { locale: 'tr', language: 'Turkish', today: 'Bugün', tomorrow: 'Yarın' },
  { locale: 'uk', language: 'Ukrainian', today: 'Сьогодні', tomorrow: 'Завтра' },
  { locale: 'ur', language: 'Urdu', today: 'آج', tomorrow: 'کل' },
  { locale: 'ug-cn', language: 'Uyghur (China)', today: 'بۈگۈن', tomorrow: 'ئەتە' },
  { locale: 'uz', language: 'Uzbek', today: 'Бугун', tomorrow: 'Эртага' },
  { locale: 'uz-latn', language: 'Uzbek Latin', today: 'Bugun', tomorrow: 'Ertaga' },
  { locale: 'vi', language: 'Vietnamese', today: 'Hôm nay', tomorrow: 'Ngày mai' },
  { locale: 'cy', language: 'Welsh', today: 'Heddiw', tomorrow: 'Yfory' },
  { locale: 'yo', language: 'Yoruba Nigeria', today: 'Owọ́́n', tomorrow: 'Ọ̀la' },
  { locale: 'ss', language: 'siSwati', today: 'Namuhla', tomorrow: 'Kusasa' },
  { locale: 'pt-PT', language: 'Português', today: 'Hoje', tomorrow: 'Amanhã' },
];

export const SESSION_STORAGE_KEY = {
  START_TIME_FOR_SHOP_CUSTOM_3H_LEFT: 'ot-start-time-for-shop-custom-3h-left',
  START_TIME_FOR_SHOP_CUSTOM_30_MINUTES_LEFT: 'ot-start-time-for-shop-custom-30-minutes-left',
};

export const ALL_STATE_VALUE = '---';

export const SAMPLE_DATA: IShopifyAppMetafieldPayload = {
  rootLink: 'https://order-limiter-dev.synctrack.ioo/api',
  data: {
    settings: {
      id: 4547,
      shop: 'linhtmq-dev.myshopify.com',
      layout: ShopLayout.ShippingRule,
      lastAccess: 1738912028,
      oldPlan: 'free' as PricingPlan,
      plan: 'pro' as PricingPlan,
      subscription: 'monthly' as PlanSubscription,
      planUpdatedAt: 1626664916,
      displayOnboarding: false,
      script_tag_id: '178414125216',
      week_working_days:
        '{"prepareAndDelivery":[{"enable":0,"cut_off_after":"23:59","day":0},{"enable":0,"cut_off_after":"23:59","day":1},{"enable":1,"cut_off_after":"11:59","day":2},{"enable":1,"cut_off_after":"11:59","day":3},{"enable":1,"cut_off_after":"11:59","day":4},{"enable":1,"cut_off_after":"11:59","day":5},{"enable":0,"cut_off_after":"23:59","day":6}],"prepare":[{"enable":1,"cut_off_after":"23:59","day":0},{"enable":0,"cut_off_after":"23:59","day":1},{"enable":0,"cut_off_after":"23:59","day":2},{"enable":0,"cut_off_after":"13:59","day":3},{"enable":0,"cut_off_after":"08:59","day":4},{"enable":0,"cut_off_after":"23:59","day":5},{"enable":0,"cut_off_after":"23:59","day":6}],"delivery":[{"enable":1,"cut_off_after":"23:59","day":0},{"enable":0,"cut_off_after":"23:59","day":1},{"enable":0,"cut_off_after":"23:59","day":2},{"enable":0,"cut_off_after":"23:59","day":3},{"enable":0,"cut_off_after":"23:59","day":4},{"enable":0,"cut_off_after":"23:59","day":5},{"enable":0,"cut_off_after":"23:59","day":6}]}',
      isUseSeparateWorkingDays: false,
      specific_day_off: '[]',
      position_code: 2,
      custom_css: '',
      show_on_line_item: 0,
      show_on_pages: 'product_page,collections,pages,home',
      custom_position: '',
      render_method: 'append',
      enable_app: 1,
      disable_when_product_is_out_of_stock: 0,
      date_timezone_offset: '',
      type_time_countdown: 1,
      textCountDownFormat: '🚚 Same Day fulfilment cut off in {TimeCountDown}: Order Now!',
      countdown_timer_option: CountdownTimerOption.NextCutoff,
      countdown_timer_show_after_cutoff: true,
      days: 'day(s)',
      hours: 'hrs',
      minutes: 'mins',
      seconds: 'secs',
      require_add_to_cart: 0,
      isHiddenCountryRulesNotDetected: false,
      clientJsUrl: 'development',
      choose_layout: 'card',
      labelCheckout: 'Order limiter between',
      get_customer_zipcode: 1,
      created_at: null,
      updated_at: null,
      text_size: 11,
      text_color: '#000000',
      icon_color: '#4B5563',
      border_color: '#D1D5DB',
      background_color: '#F3F4F6',
      show_shipping_method: false,
      shippingMethodLabel: 'Shipping method',
      enable_eta_information: true,
      enable_timeline_layout: 0,
      timeline_order_step_enable: true,
      timeline_order_step_title: 'Order Placed',
      timeline_order_step_description: 'Our same day delivery cuts off at 4PM, Mon to Fri.',
      timeline_ship_step_enable: true,
      timeline_ship_step_title: 'Processing',
      timeline_ship_step_description: '',
      timeline_delivery_step_enable: true,
      timeline_delivery_step_title: 'Earliest Delivered',
      timeline_delivery_step_description: 'Based on Delivery/Collection Date Selected',
      timeline_date_range_direction: 'column' as DateRangeDirection,
      timeline_date_range_icon: '→',
      date_format: 'ddd DD MMM',
      date_locale: 'en',
      date_display_mode: 'relative' as DateDisplayMode,
      cart_page_label_text: 'Order limiter between',
      cart_page_date_display: '{delivery_min} and {delivery_max}',
      isShowDeliveryMethodName: false,
      isDynamicDateInCart: false,
      customDynamicDateInCart: '',
      themeName: '',
      themeStoreId: -1,
      detectionMethod: 'shop_locale' as DetectionMethod,
      ruleSortBy: 'id_desc' as SortOptionsEnum,
      isShowWhenInventoryNotTracked: false,
      // conditionShowCheckoutRule: 'earliest_min_preparation_date',
      dateCalculationMethod: DateCalculationMethod.MaxPreparationDate,
      timelineShipIcon: {
        iconId: 44,
        iconUrl: null,
        isCustom: false,
      },
      timelineOrderIcon: {
        iconId: 0,
        iconUrl: null,
        isCustom: false,
      },
      timelineDeliveryIcon: {
        iconId: 67,
        iconUrl: null,
        isCustom: false,
      },
    },
    zipcodeSettings: {
      id: 0,
      shop: 'trung-hieu-test-app.myshopify.com',
      inputLabel: 'Check Shipping Availability',
      inputPlaceholder: 'Enter postal code text',
      submitButton: 'Submit',
      submitButtonBackgroundColor: '#2c3e50',
      submitButtonTextColor: '#ffffff',
      zipcodeAvailableText: 'Shipping available at',
      zipcodeNotAvailableText: 'Shipping unavailable at',
    },
    rules: [
      {
        id: 6,
        shop: 'trung-hieu-test-app.myshopify.com',
        name: 'All rule',
        styledName: 'All rule',
        enable: true,
        minPrepDays: 0,
        maxPrepDays: 0,
        minDeliveryDays: 0,
        maxDeliveryDays: 1,
        estimatedText:
          '⏰ Order today within <b>{TimeCountDown}</b> to get discounted price<br>\n🚚 Delivery from <b>{delivery_min}</b> to <b>{delivery_max}</b>',
        showTextInCart: false,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          '<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it’s in stock.',
        isShowDeliveryMethodName: true,
        privacyPageUrl: 'asd',
        privacyPageText: 'asd',
        privacyMore: 'asd',
        itemConditions: [],
        locationConditions: [],
        isUsePreOrderDate: true,
        preOrderDate: '2025-02-09T17:00:00.000Z',
      },
      {
        id: 5,
        shop: 'trung-hieu-test-app.myshopify.com',
        name: 'zipcode rule',
        styledName: 'zipcode rule',
        enable: true,
        maxPrepDays: 0,
        maxDeliveryDays: 2,
        minPrepDays: 0,
        minDeliveryDays: 0,
        estimatedText:
          '⏰ Order today within <b>{TimeCountDown}</b> to get discounted price<br>\n🚚 Delivery from <b>{delivery_min}</b> to <b>{delivery_max}</b>',
        showTextInCart: false,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          '<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it’s in stock.',
        isShowDeliveryMethodName: true,
        privacyPageUrl: '',
        privacyPageText: '',
        privacyMore: '',
        itemConditions: [],
        locationConditions: [
          {
            type: LocationConditionEnum.Zipcode,
            value: [
              {
                data: '1,2,3,4,5:90,100000,60000-000:63999-999',
              },
            ],
          },
        ],
      },
      {
        id: 4,
        shop: 'trung-hieu-test-app.myshopify.com',
        name: 'Name of rule 1',
        styledName: 'Name of rule 1',
        enable: true,
        maxPrepDays: 1,
        maxDeliveryDays: 1,
        minPrepDays: 1,
        minDeliveryDays: 1,
        estimatedText:
          '⏰ Order today within <b>{TimeCountDown}</b> to get discounted price<br>\n🚚 Delivery from <b>{delivery_min}</b> to <b>{delivery_max}</b>',
        showTextInCart: false,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          '<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it’s in stock.',
        isShowDeliveryMethodName: true,
        privacyPageUrl: '',
        privacyPageText: '',
        privacyMore: '',
        itemConditions: [],
        locationConditions: [
          // {
          //   type: LocationConditionEnum.Zipcode,
          //   value: [
          //     {
          //       data: '1',
          //     },
          //   ],
          // },
        ],
      },
      {
        id: 3,
        shop: 'trung-hieu-test-app.myshopify.com',
        name: 'Name of rule 2',
        styledName: 'Name of rule 2',
        enable: true,
        maxPrepDays: 3,
        maxDeliveryDays: 5,
        minPrepDays: 2,
        minDeliveryDays: 4,
        estimatedText: '<p>ewwqqwe</p>',
        showTextInCart: true,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText: null,
        isShowDeliveryMethodName: true,
        privacyPageUrl: null,
        privacyPageText: '',
        privacyMore: null,
        itemConditions: [],
        locationConditions: [
          // {
          //   type: LocationConditionEnum.Zipcode,
          //   value: [
          //     {
          //       data: '123123',
          //     },
          //   ],
          // },
        ],
      },
      {
        id: 2,
        shop: 'trung-hieu-test-app.myshopify.com',
        name: 'Australia',
        styledName: 'Australia',
        enable: true,
        maxPrepDays: 2,
        maxDeliveryDays: 4,
        minPrepDays: 1,
        minDeliveryDays: 3,
        estimatedText:
          '⏰ Order today within <b>{TimeCountDown}</b> to get discounted price<br>\n🚚 Delivery from <b>{delivery_min}</b> to <b>{delivery_max}</b> {flag} {country}',
        showTextInCart: true,
        cartPageLabelText: 'Order limiter between 123',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: true,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          '<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it’s in stock.',
        isShowDeliveryMethodName: true,
        privacyPageUrl: 'tooltip url',
        privacyPageText: '',
        privacyMore: 'tooltip more text',
        itemConditions: [],
        locationConditions: [
          {
            type: LocationConditionEnum.Country,
            value: [
              {
                data: 'AU',
                countryStateName: 'Australia',
              },
            ],
          },
          {
            type: LocationConditionEnum.State,
            value: [
              {
                data: 'QLD',
                countryStateName: 'Queensland',
              },
              {
                data: 'NSW',
                countryStateName: 'New South Wales',
              },
            ],
          },
        ],
      },
      {
        id: 1,
        shop: 'trung-hieu-test-app.myshopify.com',
        name: 'Name of rule hguh',
        styledName: 'Name of rule hguh',
        enable: true,
        maxPrepDays: 2,
        maxDeliveryDays: 4,
        minPrepDays: 1,
        minDeliveryDays: 3,
        estimatedText:
          '⏰ Order today within <b>{TimeCountDown}</b> to get discounted price<br>\n🚚 Delivery from <b>{delivery_min}</b> to <b>{delivery_max}</b> {flag} {country}',
        showTextInCart: true,
        cartPageLabelText: 'Order limiter between 123',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: true,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          "<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it's in stock.",
        isShowDeliveryMethodName: true,
        privacyPageUrl: 'tooltip url',
        privacyPageText: '',
        privacyMore: 'tooltip more text',
        itemConditions: [],
        locationConditions: [
          {
            type: LocationConditionEnum.Country,
            value: [
              {
                data: 'AU',
                countryStateName: 'Australia',
              },
            ],
          },
          {
            type: LocationConditionEnum.State,
            value: [
              {
                data: 'QLD',
                countryStateName: 'Queensland',
              },
              {
                data: 'NSW',
                countryStateName: 'New South Wales',
              },
            ],
          },
        ],
      },
      {
        id: 15,
        shop: 'linhtmq-dev.myshopify.com',
        name: 'Viet Nam, Australia',
        styledName: 'Viet Nam, Australia',
        enable: true,
        maxPrepDays: 1,
        maxDeliveryDays: 4,
        minPrepDays: 1,
        minDeliveryDays: 1,
        estimatedText:
          '⏰ Order today within <b>{TimeCountDown}</b> to get discounted price<br>\n🚚 Delivery from <b>{delivery_min}</b> to <b>{delivery_max}</b> {flag} {country}',
        showTextInCart: false,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          '<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it’s in stock.',
        isShowDeliveryMethodName: true,
        privacyPageUrl: '',
        privacyPageText: '',
        privacyMore: '',
        itemConditions: [],
        locationConditions: [
          {
            type: LocationConditionEnum.Country,
            value: [
              {
                data: 'VN',
                countryStateName: 'Vietnam',
              },
              {
                data: 'AU',
                countryStateName: 'Australia',
              },
            ],
          },
        ],
      },
      {
        id: 14,
        shop: 'trung-hieu-test-app.myshopify.com',
        name: 'Ha Noi',
        styledName: '<font color="#ff0000"><b><u>Ha Noi</u></b></font>',
        enable: true,
        maxPrepDays: 1,
        maxDeliveryDays: 3,
        minPrepDays: 1,
        minDeliveryDays: 1,
        estimatedText:
          '⏰ Order today within <b>{TimeCountDown}</b> to get discounted price<br>\n🚚 Delivery from <b>{delivery_min}</b> to <b>{delivery_max}</b> {flag} {country}',
        showTextInCart: false,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          "<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it's in stock.",
        isShowDeliveryMethodName: true,
        privacyPageUrl: '',
        privacyPageText: '',
        privacyMore: '',
        itemConditions: [],
        locationConditions: [
          {
            type: LocationConditionEnum.Country,
            value: [
              {
                data: 'VN',
                countryStateName: 'Vietnam',
              },
            ],
          },
          {
            type: LocationConditionEnum.State,
            value: [
              {
                data: 'HN',
                countryStateName: 'Hà Nội',
              },
              {
                data: 'HN1',
                countryStateName: 'Hà Nội 1',
              },
              {
                data: 'HN2',
                countryStateName: 'Hà Nội 2',
              },
            ],
          },
        ],
      },
      {
        id: 30,
        shop: 'linhtmq-dev.myshopify.com',
        name: 'South East Asia',
        styledName: 'South East Asia',
        enable: true,
        maxPrepDays: 0,
        maxDeliveryDays: 3,
        minPrepDays: 0,
        minDeliveryDays: 0,
        estimatedText:
          '⏰ Order today within <strong style="color: #1373DC;">{TimeCountDown}</strong> to get discounted price<br>🚚 Delivery from <strong style="color: #1373DC;">{delivery_min}</strong> to <strong style="color: #1373DC;">{delivery_max}</strong> {flag} {country}',
        showTextInCart: false,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          '<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it’s in stock.',
        isShowDeliveryMethodName: true,
        privacyPageUrl: '',
        privacyPageText: '',
        privacyMore: '',
        itemConditions: [],
        locationConditions: [
          {
            type: LocationConditionEnum.Country,
            value: [
              {
                data: 'SEA',
                countryStateName: 'South East Asia',
              },
            ],
          },
        ],
      },
      {
        id: 31,
        shop: 'linhtmq-dev.myshopify.com',
        name: 'Rest of world',
        styledName: 'Rest of world',
        enable: true,
        maxPrepDays: 0,
        maxDeliveryDays: 3,
        minPrepDays: 0,
        minDeliveryDays: 0,
        estimatedText:
          '⏰ Order today within <strong style="color: #1373DC;">{TimeCountDown}</strong> to get discounted price<br>🚚 Delivery from <strong style="color: #1373DC;">{delivery_min}</strong> to <strong style="color: #1373DC;">{delivery_max}</strong> {flag} {country}',
        showTextInCart: false,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          '<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it’s in stock.',
        isShowDeliveryMethodName: true,
        privacyPageUrl: '',
        privacyPageText: '',
        privacyMore: '',
        itemConditions: [],
        locationConditions: [
          {
            type: LocationConditionEnum.Country,
            value: [
              {
                data: 'restOfWorld',
                countryStateName: 'Rest of world',
              },
            ],
          },
        ],
      },
      {
        id: 32,
        shop: 'linhtmq-dev.myshopify.com',
        name: 'All countries',
        styledName: 'All countries',
        enable: true,
        maxPrepDays: 0,
        maxDeliveryDays: 3,
        minPrepDays: 0,
        minDeliveryDays: 0,
        estimatedText:
          '⏰ Order today within <strong style="color: #1373DC;">{TimeCountDown}</strong> to get discounted price<br>🚚 Delivery from <strong style="color: #1373DC;">{delivery_min}</strong> to <strong style="color: #1373DC;">{delivery_max}</strong> {flag} {country}',
        showTextInCart: false,
        cartPageLabelText: 'Order limiter between',
        cartPageDateDisplay: '{delivery_min} and {delivery_max}',
        cartPageDateDisplayType: CartPageDateDisplayType.MessageText,
        soldOutEnabled: false,
        soldOutCustomTextEnabled: false,
        soldOutCustomText:
          '<strong>Currently unavailable.</strong><br>⏳ This item will be back in stock on... <br>🚚 Pre-order now for FREE delivery in 2-4 days once it’s in stock.',
        isShowDeliveryMethodName: true,
        privacyPageUrl: '',
        privacyPageText: '',
        privacyMore: '',
        itemConditions: [],
        locationConditions: [
          {
            type: LocationConditionEnum.Country,
            value: [
              {
                data: '*',
                countryStateName: 'All countries',
              },
            ],
          },
        ],
      },
    ],
    languages: [
      {
        id: 1,
        nameLanguage: 'Vietnamese',
        codeLanguage: 'vi',
        active: true,
        ruleContents: [
          {
            id: 6,
            name: 'Tất cả',
            estimatedText:
              '⏰ Đặt hàng hôm nay trong vòng <b>{TimeCountDown}</b> để được giảm giá<br>\n🚚 Giao hàng từ <b>{delivery_min}</b> đến <b>{delivery_max}</b>',
            privacyPageText: 'Chính sách bảo mật',
            privacyMore: 'Xem thêm',
            cartPageLabelText: 'Dự kiến giữa',
            cartPageDateDisplay: '{delivery_min} đến {delivery_max}',
            soldOutCustomText:
              '<strong>Hiện không có sẵn.</strong><br>⏳ Mặt hàng sẽ trở lại kho hàng vào... <br>🚚 Đặt hàng ngay để nhận giao hàng miễn phí trong 2-4 ngày khi nó trở lại kho hàng.',
          },
        ],
        appearanceContent: {
          timelineOrderStepTitle: 'Đặt hàng',
          timelineOrderStepDescription: 'Đặt hàng',
          timelineShipStepTitle: 'Giao hàng',
          timelineShipStepDescription: 'Giao hàng',
          timelineDeliveryStepTitle: 'Giao hàng',
          timelineDeliveryStepDescription: 'Giao hàng',
          inputLabel: 'Nhập zipcode',
          inputPlaceholder: 'Nhập zipcode',
          zipcodeAvailableText: 'Zipcode có sẵn',
          zipcodeNotAvailableText: 'Zipcode không có sẵn',
          submitButton: 'Gửi',
          days: 'ngày',
          hours: 'giờ',
          minutes: 'phút',
          seconds: 'giây',
          shippingMethodLabel: 'Phương thức vận chuyển',
        },
        checkoutContent: {
          checkoutRules: [],
        },
      },
    ],
  },
  isABTest: true,
};
