export enum WixEventType {
  APP_INSTALLED = 'AppInstalled',
  APP_REMOVED = 'AppRemoved',
  PLAN_PURCHASED = 'PaidPlanPurchased',
  PLAN_CHANGED = 'PaidPlanChanged',
  PLAN_CANCELLED = 'PaidPlanAutoRenewalCancelled',
  SITE_UPDATE = 'SitePropertiesUpdated',
  ORDER_CREATED = 'com.wix.ecommerce.orders.api.v2.OrderEvent',
  ECOM_FULFILLMENTS_STATUS_UPDATE = 'wix.ecom.v1.fulfillments_updated',
  ECOM_ORDER_FULFILLED = 'wix.ecom.v1.order_fulfilled',
  ECOM_ORDER_TRANSACTION_UPDATE = 'wix.ecom.v1.order_transactions_updated',
  ECOM_ORDER_PAYMENT_STATUS_UPDATE = 'wix.ecom.v1.order_payment_status_updated',
  ECOM_ORDER_UPDATE = 'wix.ecom.v1.order_updated',
}

export enum WixBillingCycle {
  NO_CYCLE = 'NO_CYCLE',
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
  ONE_TIME = 'ONE_TIME',
  TWO_YEARS = 'TWO_YEARS',
  THREE_YEARS = 'THREE_YEARS',
  FOUR_YEARS = 'FOUR_YEARS',
  FIVE_YEARS = 'FIVE_YEARS',
}

export enum WixOrderPaymentStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  UNSPECIFIED_PAYMENT_STATUS = 'UNSPECIFIED_PAYMENT_STATUS',
  PENDING = 'PENDING',
  NOT_PAID = 'NOT_PAID',
  PAID = 'PAID',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  FULLY_REFUNDED = 'FULLY_REFUNDED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
}

export enum WixFulfilledStatus {
  NOT_FULFILLED = 'NOT_FULFILLED',
  FULFILLED = 'FULFILLED',
  CANCELED = 'CANCELED',
  PARTIALLY_FULFILLED = 'PARTIALLY_FULFILLED',
}

export enum WixWeightUnit {
  UNSPECIFIED_WEIGHT_UNIT = 'UNSPECIFIED_WEIGHT_UNIT',
  KG = 'KG',
  LB = 'LB',
}

export enum WixLineItemType {
  UNSPECIFIED_LINE_ITEM_TYPE = 'UNSPECIFIED_LINE_ITEM_TYPE',
  PHYSICAL = 'PHYSICAL',
  DIGITAL = 'DIGITAL',
  CUSTOM_AMOUNT_ITEM = 'CUSTOM_AMOUNT_ITEM',
  UNRECOGNISED = 'UNRECOGNISED',
  GIFT_CARD = 'GIFT_CARD',
  SERVICE = 'SERVICE',
}

export enum WixActivityType {
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  UNSPECIFIED_ORDER_HISTORY_ITEM_TYPE = 'UNSPECIFIED_ORDER_HISTORY_ITEM_TYPE',
  MERCHANT_COMMENT = 'MERCHANT_COMMENT',
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_PAID = 'ORDER_PAID',
  ORDER_FULFILLED = 'ORDER_FULFILLED',
  ORDER_NOT_FULFILLED = 'ORDER_NOT_FULFILLED',
  DOWNLOAD_LINK_SENT = 'DOWNLOAD_LINK_SENT',
  PICKUP_READY_EMAIL_SENT = 'PICKUP_READY_EMAIL_SENT',
  TRACKING_NUMBER_ADDED = 'TRACKING_NUMBER_ADDED',
  TRACKING_NUMBER_EDITED = 'TRACKING_NUMBER_EDITED',
  TRACKING_LINK_WAS_SET = 'TRACKING_LINK_WAS_SET',
  SHIPPING_CONFIRMATION_EMAIL_SENT = 'SHIPPING_CONFIRMATION_EMAIL_SENT',
  INVOICE_WAS_SET = 'INVOICE_WAS_SET',
  INVOICE_WAS_REMOVED = 'INVOICE_WAS_REMOVED',
  INVOICE_WAS_SENT = 'INVOICE_WAS_SENT',
  FULFILLER_EMAIL_SENT = 'FULFILLER_EMAIL_SENT',
  SHIPPING_ADDRESS_EDITED = 'SHIPPING_ADDRESS_EDITED',
  EMAIL_EDITED = 'EMAIL_EDITED',
  ORDER_PARTIALLY_PAID = 'ORDER_PARTIALLY_PAID',
  ORDER_CANCELED = 'ORDER_CANCELED',
  TRACKING_LINK_ADDED = 'TRACKING_LINK_ADDED',
  INVOICE_ADDED = 'INVOICE_ADDED',
  INVOICE_REMOVED = 'INVOICE_REMOVED',
  INVOICE_SENT = 'INVOICE_SENT',
  CUSTOM_ACTIVITY = 'CUSTOM_ACTIVITY',
  ORDER_CREATED_FROM_EXCHANGE = 'ORDER_CREATED_FROM_EXCHANGE',
  NEW_EXCHANGE_ORDER_CREATED = 'NEW_EXCHANGE_ORDER_CREATED',
  DRAFT_ORDER_CHANGES_APPLIED = 'DRAFT_ORDER_CHANGES_APPLIED',
}

export enum WixVatType {
  UNSPECIFIED_TAX_TYPE = 'UNSPECIFIED_TAX_TYPE',
  CPF = 'CPF',
  CNPJ = 'CNPJ',
}

export enum TransactionPaymentStatus {
  UNDEFINED = 'UNDEFINED',
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  PENDING_MERCHANT = 'PENDING_MERCHANT',
  CANCELED = 'CANCELED',
  DECLINED = 'DECLINED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  AUTHORIZED = 'AUTHORIZED',
  VOIDED = 'VOIDED',
}

export enum WixProductType {
  PHYSICAL = 'physical',
  DIGITAL = 'digital',
}
